# Generated by Django 2.1.3 on 2018-12-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreNovia', models.CharField(max_length=45)),
                ('nombreNovio', models.CharField(max_length=45)),
                ('numeroContacto', models.CharField(max_length=45)),
                ('emailContacto', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='comunidad',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='boda',
            name='tipoParroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comunidad'),
        ),
    ]
