# Generated by Django 2.1.3 on 2018-12-03 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bautizo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('edad', models.CharField(max_length=45)),
                ('numeroContacto', models.CharField(max_length=45)),
                ('emailContacto', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('tipoParroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comunidad')),
            ],
        ),
    ]
