# Generated by Django 2.1.3 on 2018-12-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181203_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidadcatolica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreComunidad', models.CharField(max_length=45)),
            ],
        ),
    ]
