# Generated by Django 2.1.4 on 2018-12-17 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ministro'),
    ]

    operations = [
        migrations.CreateModel(
            name='BautizoSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bautizado', models.CharField(max_length=45)),
                ('edad', models.CharField(max_length=45)),
                ('padrino', models.CharField(max_length=45)),
                ('madrina', models.CharField(max_length=45)),
                ('tipoParroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='BodaSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreNovia', models.CharField(max_length=45)),
                ('nombreNovio', models.CharField(max_length=45)),
                ('numeroContacto', models.CharField(max_length=45)),
                ('emailContacto', models.CharField(max_length=45)),
                ('tipoParroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='ComunionSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreComunion', models.CharField(max_length=45)),
                ('edad', models.CharField(max_length=45)),
                ('numeroContacto', models.CharField(max_length=45)),
                ('emailContacto', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('tipoParroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comunidad')),
            ],
        ),
    ]
